
# ??? ??? ??
crawling:
  sites:
    daum:
      url: "https://news.daum.net/"
      selectors:
        depth1: "div.box_comp.box_news_headline2"
        depth2: "ul.list_newsheadline2 > li"
      data-selectors:
        wrapper: "div.main-content"
        title: "h3.tit_view"
        content: "div.article_view"
        publisher: "div.news_view.fs_type1 > p"
        createAt: "div.info_view span.num_date"
        comment: "div.util_wrap a.btn_ttalk"
        emoticon: "div.inner_emoticon"
      recursive-data-selectors:
        wrapper: "div.box_cluster.box_news_recomm ul.list_column"
        url: "div.item_column > a"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crawling?options=-c%20search_path=public
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: 127.0.0.1:10000, 127.0.0.1:10001, 127.0.0.1:10002
    consumer:
      group-id: hb
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: alfhaos489@gmail.com
    password: vtde zpyq xzpz zuaf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
agent:
  role: default
  topic: newsCrawling
  target: colin.h.jeong@selvas.com
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.news.newscrawling.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    org.apache.ibatis: debug

server:
  port: 8081